[package]
name = "real_time_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

<<<<<<< HEAD

[build-dependencies]
bindgen = "*"
=======
[build-dependencies]
bindgen = "0.53.1"
>>>>>>> main
