[package]
name = "real_time_project"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"


[build-dependencies]
bindgen = "*"
